apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.secretName }}
  labels:
    {{- include "animal-image-app.common-labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}