# Default values for animal-image-app.

# Define container environment variables using secret data
env:
  secretName: animal-image-app-secret
  secret:
    ZEEBE_REST_ADDRESS: https://syd-1.zeebe.camunda.io/7a12d381-80a3-4a0d-a86c-31cba730f5bb
    CAMUNDA_TOKEN_AUDIENCE: zeebe.camunda.io
    CAMUNDA_CLIENT_ID: F-7-8s0.Bw3Vji7OlJiXzLxvKgxFGLGN
    CAMUNDA_CLIENT_SECRET: gLwyE~qJ5WErO~RXqQt0I5aQaWGw7x8k_4.6szM8lwhDJeWV~i_9pGIr20UU4REP
    CAMUNDA_OAUTH_URL: https://login.cloud.camunda.io/oauth/token
    FLASK_SESSION_SECRET_KEY: scorm/3o9btmgnh45l1

# Sets the image values for the container
image:
  repository: deeshal/animal-image-app
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.11"

# Sets the image values for the job worker container
jobWorker:
  name: job-worker
  image:
    repository: deeshal/job-worker
    # This sets the pull policy for images.
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.11"

# This is for the secrets for pulling an image from a private repository
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "animal-image-app"

service:
  type: ClusterIP
  port: 5000

# Controls the number of animal-image-app pods spun by the deployment
replicaCount: 1

# This is for setting Kubernetes Annotations to a Pod.
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
podLabels: {}